apiVersion: v1
kind: Service
metadata:
  name: blogginrose-ui
  labels:
    app: blogginrose-ui
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30004
      protocol: TCP
  selector:
    app: blogginrose-ui
